[package]
name = "yarlox-interpreter"
default-run = "yarlox-interpreter"
version = "1.0.0"
authors = ["Brian Gavin <bgavin1996@gmail.com>"]

[dependencies]
lazy_static = "1.1.0"
log = "0.4"
env_logger = "0.5"
rustyline = "5"
ansi_term = "0.12"
